fix: Fix compilation error
Fixed 'TSError: ⨯ Unable to compile TypeScript - Property 'volume' has no initializer and is not definitely assigned in the constructor'. The cause is due to not initializing defined attributes in constructor.